#!bin/bash
source lib.sh
source env.sh

#ipsec strongswab
CMD_IPSec_HQ='
DEBIAN_FRONTEND=noninteractive apt-get install strongswan -y

cat > /etc/ipsec.conf <<EOF
config setup
        uniqueids=yes

conn hq-br
        left=172.16.1.2
        right=172.16.2.2
        auto=start
        type=transport
        keyexchange=ikev2
        ike=aes256-sha256-modp2048
        esp=aes256-sha256
        authby=psk
        mobile=no
include /var/lib/strongswan/ipsec.conf.inc
EOF
echo "172.16.4.2 172.16.5.2 : PSK \"P@ssw0rd\">> /etc/ipsec.secrets
systemctl restart strongswan
'
vm_exec $ID_HQ_RTR "$CMD_IPSec_HQ" "test ipsec hq"

CMD_IPSec_BR='
DEBIAN_FRONTEND=noninteractive apt-get install strongswan -y

cat > /etc/ipsec.conf <<EOF
config setup
        uniqueids=yes

conn br-hq
        left=172.16.2.2
        right=172.16.1.2
        auto=start
        type=transport
        keyexchange=ikev2
        ike=aes256-sha256-modp2048
        esp=aes256-sha256
        authby=psk
        mobile=no
include /var/lib/strongswan/ipsec.conf.inc
EOF
echo "172.16.4.2 172.16.5.2 : PSK \"P@ssw0rd\">> /etc/ipsec.secrets
systemctl restart strongswan
ipsec up br-hq
'
vm_exec $ID_BR_RTR "$CMD_IPSec_BR" "test ipsec br"

# firewall
CMD_FIREWALL_HQ='
touch /etc/iptables.rules
cat > /etc/iptables.rules <<EOF
# Generated by iptables-save v1.6.2 on Tue June 16 17:03:20 2026
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [1:51]
:POSTROUTING ACCEPT [1:51]
-A PREROUTING -d 172.16.1.0/28 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.1.2:8080
-A PREROUTING -d 172.16.1.0/28 -p tcp -m tcp --dport 2026 -j DNAT --to-destination 192.168.1.2:2026
-A POSTROUTING -s 192.168.1.0/27 -o eth0 -j MASQUERADE
COMMIT
# Completed on Tue June 16 17:03:20 2026
# Generated by iptables-save v1.6.2 on Tue June 16 17:03:20 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [56:5600]
:OUTPUT ACCEPT [349:24512]
-A INPUT -p tcp -m tcp --dport 2026 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 123 -j ACCEPT
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -s 10.0.0.0/30 -j ACCEPT
-A INPUT -s 172.16.1.0/28 -j ACCEPT
-A INPUT -p esp -j ACCEPT
-A INPUT -j DROP
COMMIT
# Completed on Tue June 16 17:03:20 2026
EOF
iptables-restore << /etc/iptables.rules
'
vm_exec $ID_HQ_RTR "$CMD_FIREWALL_HQ" "firewall hq"

CMD_FIREWALL_BR='
cat > /etc/iptables.rules <<EOF
# Generated by iptables-save v1.6.2 on Mon Jun 16 17:15:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [113:12860]
:OUTPUT ACCEPT [151:14330]
-A INPUT -p tcp -m tcp --dport 2026 -j ACCEPT
-A INPUT -p tcp -m tcp --sport 53 -j ACCEPT
-A INPUT -p udp -m udp --sport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 123 -j ACCEPT
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -s 10.0.0.1/32 -j ACCEPT
-A INPUT -s 172.16.1.2/32 -j ACCEPT
-A INPUT -p esp -j ACCEPT
-A INPUT -j DROP
COMMIT
# Completed on Mon Jun 16 17:15:00 2026
# Generated by iptables-save v1.6.2 on Mon Jun 16 17:15:00 2026
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [3:207]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -d 172.16.2.2/32 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.3.2:8080
-A PREROUTING -d 172.16.2.2/32 -p tcp -m tcp --dport 2026 -j DNAT --to-destination 192.168.3.2:2026
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.3.0/28 -o eth0 -j MASQUERADE
COMMIT
# Completed on Mon Jun 16 17:15:00 2026
EOF
iptables-restore << /etc/iptables.rules
'
vm_exec $ID_BR_SRV "$CMD_FIREWALL_BR" "firewall br"

#cups print srv
CMD_CUPS_SRV='
apt-get install cups cups-pdf -y
systemctl enable --now cups 
sed -i 's/Listen localhost:631/0.0.0.0:631/' /etc/cups/cupsd.conf
sed -i '/<Location \/>/a\        Allow from all' /etc/cups/cupsd.conf
sed -i '/<Location \/admin>/a\        Allow from all' /etc/cups/cupsd.conf
sed -i 's/^Out \${DESKTOP}/\#Out \${DESKTOP}/' /etc/cups/cups-pdf.conf
sed -i 's/^\#Out \/var\/spool\/cups-pdf\/\${USER}/Out \/var\/spool\/cups-pdf\/\${USER}/' /etc/cups/cups-pdf.conf
cupsctl --remote-any
systemctl restart cups
echo "test from hq-srv" | lp -d CUPS-PDF
'

vm_exec $ID_HQ_SRV "$CMD_CUPS_SRV" "print srv hq"

CMD_CUPS_CLI='
echo "test from hq-cli" | lp -h hq-srv -d CUPS-PDF
'
vm_exec $ID_HQ_CLI "$CMD_CUPS_CLI" "test print srv from hq-cli"

